# Generated by Django 4.2.9 on 2024-02-01 17:44

import devices.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="grafana_dashboards",
            field=models.JSONField(
                default=devices.models.default_dashboards_json_field,
                verbose_name="Dashboards json field",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("uid",), name="unique_uid_blocking"
            ),
        ),
    ]
