# Generated by Django 4.2.11 on 2024-03-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_device_foxglove_dashboards"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="public_ssh_key",
            field=models.TextField(
                default="", verbose_name="device public SSH key"
            ),
        ),
    ]
