# Generated by Django 4.2.9 on 2024-02-19 10:07

import devices.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "devices",
            "0002_device_grafana_dashboards_device_unique_uid_blocking",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="foxglove_layouts",
            field=models.JSONField(
                default=devices.models.default_layouts_json_field,
                verbose_name="Foxglove layouts json field",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="grafana_dashboards",
            field=models.JSONField(
                default=devices.models.default_dashboards_json_field,
                verbose_name="Grafana dashboards json field",
            ),
        ),
    ]
