# Generated by Django 4.2.18 on 2025-01-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_lokialertrulefile_prometheusalertrulefile"),
        ("devices", "0003_device_public_ssh_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="prometheus_alert_rule_files",
            field=models.ManyToManyField(
                related_name="devices", to="applications.prometheusalertrulefile"
            ),
        ),
    ]
