# Generated by Django 4.2.10 on 2025-01-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_alter_lokialertrule_rules_and_more"),
        ("devices", "0003_device_public_ssh_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="prometheus_alert_rules",
            field=models.ManyToManyField(
                related_name="devices", to="applications.prometheusalertrule"
            ),
        ),
    ]
