# Generated by Django 4.2.18 on 2025-02-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_lokialertrulefile_prometheusalertrulefile"),
        ("devices", "0004_device_prometheus_alert_rule_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="loki_alert_rule_files",
            field=models.ManyToManyField(
                related_name="devices", to="applications.lokialertrulefile"
            ),
        ),
    ]
