# Generated by Django 4.2.18 on 2025-01-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_device_prometheus_alert_rules"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="prometheus_alert_rules",
            new_name="prometheus_rules_files",
        ),
    ]
