# Generated by Django 4.2.23 on 2025-08-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_device_loki_alert_rule_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="generate_certificate",
            field=models.BooleanField(
                default=False,
                verbose_name="whether to generate a device TLS certificate",
            ),
        ),
    ]
