# Generated by Django 4.2.26 on 2026-01-16 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_device_loki_alert_rule_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="certificate",
                        serialize=False,
                        to="devices.device",
                    ),
                ),
                (
                    "csr",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Certificate Signing Request",
                    ),
                ),
                (
                    "certificate",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Signed Certificate",
                    ),
                ),
                (
                    "ca",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Certificate Authority",
                    ),
                ),
                (
                    "chain",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Certificate Chain",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("signed", "Signed"),
                            ("denied", "Denied"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Certificate request created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Certificate last updated"
                    ),
                ),
            ],
        ),
    ]
