# Generated by Django 4.2.26 on 2026-01-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_device_loki_alert_rule_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="certificate",
                        serialize=False,
                        to="devices.device",
                    ),
                ),
                (
                    "csr",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Certificate Signing Request",
                    ),
                ),
                (
                    "certificate",
                    models.TextField(
                        blank=True, default="", verbose_name="Signed Certificate"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("signed", "Signed"),
                            ("denied", "Denied"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True, default="", verbose_name="Certificate details"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Certificate request created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Certificate last updated"
                    ),
                ),
            ],
        ),
    ]
