# Generated by Django 4.2.26 on 2026-01-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_device_loki_alert_rule_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="certificate",
            field=models.TextField(
                blank=True, default="", verbose_name="Signed Certificate"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="certificate_created_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Certificate request created",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="certificate_detail",
            field=models.TextField(
                blank=True, default="", verbose_name="Certificate details"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="certificate_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("signed", "Signed"),
                    ("denied", "Denied"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="certificate_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Certificate last updated"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="csr",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Certificate Signing Request",
            ),
        ),
    ]
