# Generated by Django 4.2.11 on 2024-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoxgloveDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=200, unique=True)),
                (
                    "dashboard",
                    models.JSONField(verbose_name="Dashboard json field"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
