# Generated by Django 4.2.18 on 2025-01-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_foxglovedashboard"),
    ]

    operations = [
        migrations.CreateModel(
            name="LokiAlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=200, unique=True)),
                ("rules", models.TextField()),
                (
                    "template",
                    models.BooleanField(
                        default=False,
                        verbose_name="Whether this rules file is a template and must be rendered",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PrometheusAlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=200, unique=True)),
                ("rules", models.TextField()),
                (
                    "template",
                    models.BooleanField(
                        default=False,
                        verbose_name="Whether this rules file is a template and must be rendered",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
