# Generated by Django 4.2.10 on 2025-01-23 11:58

import applications.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_lokialertrule_prometheusalertrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lokialertrule",
            name="rules",
            field=applications.fields.YAMLField(),
        ),
        migrations.AlterField(
            model_name="lokialertrule",
            name="template",
            field=models.BooleanField(
                default=False,
                verbose_name="Whether this rules file is                                    a template and must be rendered",
            ),
        ),
        migrations.AlterField(
            model_name="prometheusalertrule",
            name="rules",
            field=applications.fields.YAMLField(),
        ),
        migrations.AlterField(
            model_name="prometheusalertrule",
            name="template",
            field=models.BooleanField(
                default=False,
                verbose_name="Whether this rules file is                                    a template and must be rendered",
            ),
        ),
    ]
