name: cos-registration-server
summary: The COS registration server
description: |
        COS registation server with production server
        and static fileserver
version: '0.1'
base: core22
confinement: strict

parts:
  cos-registration-server:
    plugin: python
    source: .
    python-packages: ["django"]
    override-build: |
      craftctl default
      cd $CRAFT_PART_INSTALL/lib/python3.10/site-packages/cos_registration_server
      PYTHONPATH=../ python3 manage.py collectstatic --no-input

  local:
    plugin: dump
    source: snap/local
    organize:
      '*.bash' : usr/bin/

apps:
  cos-registration-server:
    command: usr/bin/launcher.bash
    daemon: simple
    plugs:
      - network
      - network-bind
